[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#C8A43B"
backgroundColor = "#F5F0E8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"
